services:
    wmm-web:
        image: p3000/asu-cds-wmm:latest
        ports:
            - "4200:4200"
    wmm-hapi-fhir:
        image: hapiproject/hapi:v8.2.0-1
        ports:
            - "8080:8080"
        environment:
            - hapi.fhir.fhir_version=R4
            - spring.main.allow-bean-definition-overriding=true
            - hapi.fhir.expunge_enabled=true
            - hapi.fhir.allow_multiple_delete=true
            - hapi.fhir.bulk_export_enabled=true
            - hapi.fhir.bulk_import_enabled=true
            - hapi.fhir.enable_index_missing_fields=true
            - hapi.fhir.cdshooks.enabled=true
            - hapi.fhir.cr.enabled=true
